### PR TITLE
Hybris sony aosp 8.1.0 r52 20190206 upstream updates

### LINKED ISSUE #1997: Latest update on LA.UM.6.4.r1 broke compilation
The latest update to LA.UM.6.4.r1 brought the commit:
e5d7620af2fd50b50c3a37cd7a27e366e897747

Which results in
```
../../../../../../kernel/sony/msm-4.4/kernel/drivers/platform/msm/ipa/ipa_v3/ipa_rt.c: In function 'ipa3_reset_rt':
../../../../../../kernel/sony/msm-4.4/kernel/drivers/platform/msm/ipa/ipa_v3/ipa_rt.c:1473:13: error: 'struct ipa3_rt_entry' has no member named 'rule_id_valid'
    if (!rule->rule_id_valid)
             ^
make[6]: *** [drivers/platform/msm/ipa/ipa_v3/ipa_rt.o] Error 1
make[6]: *** Waiting for unfinished jobs....

```
The issue is that /rule_id_valid/ was only added in:
https://github.com/sonyxperiadev/kernel/commit/d0c2a1ebcecc549d1803787c1c9d78f3ed308a9e

Which is not inside this true.
So what should happen revert the commit or apply depended commit?

### PR DESCRIPTION
**Pull request by Thaodan**
- latest updates from stable 4.4.y
- Fixes SONYxperiadev#1997                                                       
- Add the ability to the revert display panel firmware                             
  (SOnyxperiadev Pull #2007)

### CODE REVIEW

**Comment by Thaodan** [comment]
updated with more changes from upstream

**Comment by Thaodan** [comment]
Broken by:
https://github.com/sonyxperiadev/kernel/issues/1997

**Comment by Thaodan** [comment]
depends on:
https://github.com/sonyxperiadev/kernel/pull/1998

**Comment by Thaodan** [comment]
Updated please review :)

**Comment by mkosola** [comment]
Thank you, will test.

**Review by mkosola — APPROVED** [review]
Thank you, LGTM

**Pull request merged**
