### PR TITLE
[config] Enable iptables match options. Contributes to JB#44783.

### PR DESCRIPTION
**Pull request by ballock**

### CODE REVIEW

**Comment by LaakkonenJussi** [comment]
Could you enable also CONFIG_IP6_NF_MATCH_AH as it is required for IPv6 AH protocol match.

Also, I’d suppose CONFIG_IP_DCCP and CONFIG_IP_SCTP would be required for those protocols to work (?).

**Comment by ballock** [comment]
CONFIG_IP6_NF_MATCH_AH added.

**Comment by ballock** [comment]
I also verified that the effective complete .config file contains all the matches as required.

**Comment by ballock** [comment]
I left out CONFIG_IP_DCCP and CONFIG_IP_SCTP.

**Review by LaakkonenJussi — APPROVED** [review]
LGTM

**Review by mkosola — APPROVED** [review]

**Pull request merged**
