### PR TITLE
Merge upstream changes. JB#42213

### PR DESCRIPTION
**Pull request by krnlyng**

### CODE REVIEW

**Comment by mkosola** [comment]
Conflict arch/arm64/configs/aosp_nile_pioneer_defconfig?

**Comment by krnlyng** [comment]
@mkosola Yes :).

I was doing a trick, jb42213 is not actually a hybris branch but a copy of the upstream branch.

So my intention was to merge the upstream branch with no changes into our branch and use github UI to resolve conflicts such that i can avoid most of the manual steps ;).

There is only one very small conflict.

But i can do it normally if prefered :).

**Comment by mkosola** [comment]
Ah, ok then

**Review by mkosola — APPROVED** [review]

**Review by sledges — COMMENTED** [review]
I'll approve when conflict's resolved :D

**Review by sledges — APPROVED** [review]
:D

**Comment by krnlyng** [comment]
@sledges ah!

I assumed conflicts need to be resolved *while* merging..... because the button after the resolving said: "commit merge" :D

**Pull request merged**
