### PR TITLE
[hybris/aosp/LA.UM.9.12.r1] Update from upstream

### PR DESCRIPTION
**Pull request by Thaodan**
Fixes for Xperia 10 III/Lena 2nd SIM slot and other changes.

### CODE REVIEW

**Review by krnlyng — APPROVED** [review]

**Comment by sledges** [comment]
Tested the tree when this PR was created at [e718cae](https://github.com/sonyxperiadev/kernel/commits/e718cae4b3eea810076c24b21d23c45d5c7cc085), SIM1 and SIM2 are working correctly.

However, when testing the latest build from [12b66f7](https://github.com/sonyxperiadev/kernel/commits/12b66f7f922282512f222070cae16f983e4d151b), only SIM2 slot is visible, and is identified as SIM1.

Means a regression happened somewhere between those [e718cae..12b66f7](https://github.com/sonyxperiadev/kernel/compare/e718cae4b3eea810076c24b21d23c45d5c7cc085..12b66f7f922282512f222070cae16f983e4d151b).

**Comment by Thaodan** [comment]
> Tested the tree when this PR was created at [e718cae](https://github.com/sonyxperiadev/kernel/commits/e718cae4b3eea810076c24b21d23c45d5c7cc085), SIM1 and SIM2 are working correctly.
> 
> However, when testing the latest build from [12b66f7](https://github.com/sonyxperiadev/kernel/commits/12b66f7f922282512f222070cae16f983e4d151b), only SIM2 slot is visible, and is identified as SIM1.
> 
> Means a regression happened somewhere between those [e718cae..12b66f7](https://github.com/sonyxperiadev/kernel/compare/e718cae4b3eea810076c24b21d23c45d5c7cc085..12b66f7f922282512f222070cae16f983e4d151b).

Please update upstream bug and notify @bartcubbins

**Comment by sledges** [comment]
> > Tested the tree when this PR was created at [e718cae](https://github.com/sonyxperiadev/kernel/commits/e718cae4b3eea810076c24b21d23c45d5c7cc085), SIM1 and SIM2 are working correctly.
> > However, when testing the latest build from [12b66f7](https://github.com/sonyxperiadev/kernel/commits/12b66f7f922282512f222070cae16f983e4d151b), only SIM2 slot is visible, and is identified as SIM1.
> > Means a regression happened somewhere between those [e718cae..12b66f7](https://github.com/sonyxperiadev/kernel/compare/e718cae4b3eea810076c24b21d23c45d5c7cc085..12b66f7f922282512f222070cae16f983e4d151b).
> 
> Please update upstream bug and notify @bartcubbins

This was tested on SFOS (which required additional binder changes), not on AOSP

**Comment by Thaodan** [comment]
> 

Hm that might be the case need to test.

**Comment by bartcubbins** [comment]
SDM845/Tama bringup does not affect sim detection in any way. Please test more closely the changes in the `drivers/misc/sony_ext_uim_ctrl.c`

**Review by sledges — APPROVED** [review]
> However, when testing the latest build from [12b66f7](https://github.com/sonyxperiadev/kernel/commits/12b66f7f922282512f222070cae16f983e4d151b), only SIM2 slot is visible, and is identified as SIM1.

Sorry about the noise, it's some probable race condition on AOSP unaffected by this PR, will retest on SFOS when fixed upstream: https://github.com/sonyxperiadev/bug_tracker/issues/736

**Review by bartcubbins — APPROVED** [review]

**Pull request merged**
